name: Auto Update Latest Tag via API

on:
  push:
    branches:
      - master

jobs:
  create-latest-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create or update 'latest' tag via GitHub API
        run: |
          LATEST_COMMIT=$(git rev-parse HEAD)
          TAG_EXISTS=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/git/refs/tags/latest")

          if [ "$TAG_EXISTS" == "[]" ]; then
            echo "No 'latest' tag found. Creating a new tag."
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d "{\"ref\":\"refs/tags/latest\",\"sha\":\"$LATEST_COMMIT\"}" \
              "https://api.github.com/repos/${{ github.repository }}/git/refs"
          else
            echo "'latest' tag exists. Updating the tag."
            curl -X PATCH \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d "{\"sha\":\"$LATEST_COMMIT\"}" \
              "https://api.github.com/repos/${{ github.repository }}/git/refs/tags/latest"
          fi
